---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check php version
      ansible.builtin.command: php --version
      register: php_version
      changed_when: false
      failed_when:
        - "'5.6' not in php_version.stdout"
